settings:
  show_prices: false
  show_popularity: true
  show_ratings: true
  following_badge_enabled: true
  unseen_state_enabled: true
  trending_enabled: true
  trending_banner_enabled: true
  promo_codes_enabled: true
  organizer_claims_enabled: true
  tag_as_badge_enabled: true
  onboarding_profile_step_enabled: true
