"""initial

Revision ID: 8af08eca287f
Revises:
Create Date: 2026-04-15 01:01:21.233143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8af08eca287f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_events',
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calendar_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_cached_events_calendar_id'), 'cached_events', ['calendar_id'], unique=False)
    op.create_index(op.f('ix_cached_events_deleted_at'), 'cached_events', ['deleted_at'], unique=False)
    op.create_table('calendar_settings',
    sa.Column('calendar_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sync_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('calendar_id')
    )
    op.create_index(op.f('ix_calendar_settings_name'), 'calendar_settings', ['name'], unique=False)
    op.create_table('event_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_views_event_id'), 'event_views', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_views_event_id'), table_name='event_views')
    op.drop_table('event_views')
    op.drop_index(op.f('ix_calendar_settings_name'), table_name='calendar_settings')
    op.drop_table('calendar_settings')
    op.drop_index(op.f('ix_cached_events_deleted_at'), table_name='cached_events')
    op.drop_index(op.f('ix_cached_events_calendar_id'), table_name='cached_events')
    op.drop_table('cached_events')
    # ### end Alembic commands ###
