"""add_sync_logs

Revision ID: cd8fd57f95ff
Revises: a1b2c3d4e5f6
Create Date: 2026-04-15 16:12:50.206464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd8fd57f95ff'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calendars_synced', sa.Integer(), nullable=False),
    sa.Column('events_upserted', sa.Integer(), nullable=False),
    sa.Column('events_deleted', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_logs')
    # ### end Alembic commands ###
