"""add_lat_lng_to_cached_events

Revision ID: eade39d48e73
Revises: 8af08eca287f
Create Date: 2026-04-15 04:33:23.177227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eade39d48e73'
down_revision: Union[str, None] = '8af08eca287f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cached_events', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('cached_events', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cached_events', 'longitude')
    op.drop_column('cached_events', 'latitude')
    # ### end Alembic commands ###
